image:
  repository: "602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/aws-efs-csi-driver"

controller:
  serviceAccount:
    create: false
    name: ${efs_csi_driver_service_account}

  serviceAccount:
    name: ${efs_csi_driver_service_account}
    annotations:
     eks.amazonaws.com/role-arn: ${efs_csi_driver_role}